import type { Config } from "tailwindcss";

export default {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#504840",
        "on-secondary": "#ffffff",
        "surface-container-high": "#ece6dc",
        "on-tertiary-fixed": "#2e1515",
        "inverse-surface": "#3a302a",
        "inverse-on-surface": "#faf5ee",
        background: "#faf5ee",
        "tertiary-fixed-dim": "#e8a0a0",
        "surface-container-low": "#f6f0e8",
        "secondary-fixed-dim": "#cec6be",
        "on-surface": "#3a302a",
        "secondary-container": "#eae2da",
        surface: "#faf5ee",
        "surface-container": "#f2ece4",
        error: "#c0392b",
        "primary-fixed": "#fbe8d8",
        secondary: "#78706a",
        "outline-variant": "#d8d0c8",
        "secondary-fixed": "#eae2da",
        "on-primary": "#ffffff",
        "on-background": "#3a302a",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#8a4518",
        "on-error": "#ffffff",
        outline: "#9a9088",
        "on-primary-fixed": "#401a08",
        "on-tertiary-container": "#3a2020",
        "on-primary-container": "#fbe8d8",
        "error-container": "#fce4e0",
        primary: "#c2652a",
        "tertiary-container": "#d47070",
        "on-secondary-fixed": "#2a2420",
        "surface-tint": "#c2652a",
        "tertiary-fixed": "#fce0e0",
        "on-tertiary-fixed-variant": "#6e3030",
        "on-secondary-container": "#605850",
        "surface-variant": "#ece6dc",
        "surface-bright": "#faf5ee",
        "on-surface-variant": "#605850",
        "inverse-primary": "#f0a878",
        "primary-container": "#e08850",
        "on-tertiary": "#ffffff",
        tertiary: "#8c3c3c",
        "primary-fixed-dim": "#f0a878",
        "on-error-container": "#7a1a10",
        "surface-dim": "#dcd6cc",
        "surface-container-highest": "#e6e0d6",
      },
      fontFamily: {
        headline: ["var(--font-garamond)"],
        body: ["var(--font-manrope)"],
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
    },
  },
  plugins: [],
} satisfies Config;
